#!/bin/bash
archwiki_link_bg='https://wiki.archlinux.org/index.php/Beginners%27_Guide/Installation#Installation'
archwiki_file_bg='~/Beginners_Guide.html#Installation'
archwiki_link_ig='https://wiki.archlinux.org/index.php/Installation_Guide'
archwiki_file_ig='~/Installation_Guide.html'

while : ; do
	dialog --no-collapse --no-shadow --colors --extra-button --ok-label 'Beginners G.' --extra-label 'Installation G.' --cancel-label 'Exit' --title 'Choose wikipage' --yesno "
Installation Guide:
A concise installation guide; aimed at experienced Arch users.

Beginners' Guide:
A guide through the whole process of installing and configuring Arch Linux; written for new or inexperienced users.
" 14 55
	case $? in
	0)	archwiki_link="$archwiki_link_bg"
		archwiki_file="$archwiki_file_bg";;
	3)	archwiki_link="$archwiki_link_ig"
		archwiki_file="$archwiki_file_ig";;
	*)	break
	esac
	dialog --no-collapse --no-shadow --no-tags --colors --ok-label 'Start' --cancel-label 'Exit' --title 'Browser selection' --menu 'Hints:
* Lynx is a popular choice, whilst elinks has more features.

* You need a working internet connection for starting the online entries.

* Links to other websites can not be loaded within the offline version.' 20 55 5 'elinks_offline' 'elinks (offline)' 'elinks_online' 'elinks (online)' 'lynx_offline' 'lynx (offline)' 'lynx_online' 'lynx (online)' '' '< Go back' 2> /tmp/selection_awm
	(( $? != 0 )) && break;
	case $(</tmp/selection_awm) in
	elinks_offline)	tmux new-session -d -s archwiki_menu "elinks $archwiki_file";;
	elinks_online)	tmux new-session -d -s archwiki_menu "elinks $archwiki_link";;
	lynx_offline)	tmux new-session -d -s archwiki_menu "lynx $archwiki_file";;
	lynx_online)	tmux new-session -d -s archwiki_menu "lynx $archwiki_link";;
	esac
tmux split-window -h
tmux select-pane -t 1
tmux swap-pane -s 1 -t 0
tmux -2 attach-session -t archwiki_menu
done

